### ISSUE TITLE
Component display is marked FAILED

### ISSUE THREAD

**Issue by zucki** [nickolay/esphome-lilygo-t547plus#15]
Library build and upload is working fine for me.
But my code does not show anything on the screen.

Log shows following
> [C][t574:053]: T547
[C][t574:053]:   Rotations: 0 °
[C][t574:053]:   Dimensions: 960px x 540px
[C][t574:054]:   Update Interval: 30.0s
**[E][component:082]:   Component display is marked FAILED**

The board is a LILYGO Screen-4.7-S3 V2.3
ESPHome is Version 2024.9.2

Thanks for helping.

Here is the relevant part of my code

```
esphome:
  name: infoscreen
  friendly_name: InfoScreen

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

external_components:
  - source: github://nickolay/esphome-lilygo-t547plus
    components: ["t547"]

font:
  - file: "gfonts://Roboto"
    id: roboto_15
    size: 15

display:
  - platform: t547
    id: t547_display
    update_interval: 30s
    lambda: |-
      it.printf(10, 10, id(roboto_15), "Hello World!");
```
